language: ruby
rvm:
  - "1.9.3"
  - "1.8.7"
notifications:
  irc: "irc.freenode.net#algollabs"
before_install:
before_script:
  - "bundle install"
script:
  - "export RACK_ENV=test && bundle exec rspec spec"